[font]
size = 9.0

[font.bold]
#Style = "bold"
family = "ComicCodeLigatures Nerd Font"

[font.italic]
#Style = "italic"
family = "ComicCodeLigatures Nerd Font"

[font.normal]
#Style = "Regular"
family = "ComicCodeLigatures Nerd Font"
